Create Context Menu Actions and customize command handling
CodeMC/Bot pull request #1
Opened 2024-04-27 22:42 UTC by Andre601

The Slash command handling has been tweaked to a own system to allow role-checking instead of permission checks.

Additionally have context menu commands been added to allow the accepting/denial of applications within the request-access channel.

2024-04-28 02:35 UTC, gmitch215 commented on src/main/java/io/codemc/bot/listeners/ModalListener.java
> +        switch(args[0]){
If possible, could use the newer `switch` statements

2024-04-28 02:40 UTC, gmitch215 requested changes
Dunno if I have authority anyways...

2024-04-28 12:37 UTC, sgdc3 requested changes

2024-04-28 12:39 UTC, Andre601 commented on src/main/java/io/codemc/bot/menu/ApplicationMenu.java
> +                    "Allowed Roles: " + String.join(", ", roleNames)
I dislike giving a "no permission" error for a lack of roles here...

2024-04-28 12:39 UTC, Andre601 commented on src/main/java/io/codemc/bot/commands/BotCommand.java
> +        System.out.println("Custom BotCommand called!");
That was for debugging.

2024-04-28 12:40 UTC, Andre601 commented on src/main/java/io/codemc/bot/utils/Constants.java
Can do, tho I personally would then use Configurate here, as it feels a bit better to use for me.

2024-04-28 14:15 UTC, Andre601 commented on src/main/java/io/codemc/bot/listeners/ModalListener.java
> +        switch(args[0]){
Switched (no pun intended) to the newer system, if you meant the `case "something" -> {...}` one.

2024-04-28 14:16 UTC, Andre601 commented on src/main/java/io/codemc/bot/listeners/ModalListener.java
> +                    CmdApplication.handle(hook, guild, messageId, text, args[1].equals("accepted"));
fixed

2024-04-28 14:30 UTC, Andre601 commented on src/main/java/io/codemc/bot/menu/ApplicationMenu.java
> +                    "Allowed Roles: " + String.join(", ", roleNames)
I now made a method to check for the roles and send a perm error message, even tho I'm still oposed to it.

2024-04-28 14:30 UTC, Andre601 commented on src/main/java/io/codemc/bot/menu/ApplicationMenu.java
> +        List<Long> roleIds = member.getRoles().stream().map(Role::getIdLong).collect(Collectors.toList());
done

2024-04-28 14:30 UTC, Andre601 commented on src/main/java/io/codemc/bot/commands/BotCommand.java
> +            boolean hasRole = false;
Used in the new utility method used.

2024-04-28 14:31 UTC, Andre601 commented on src/main/java/io/codemc/bot/utils/Constants.java
Implemented configurate now for the config and used a JSON file, because simpler.

2024-04-28 16:35 UTC, gmitch215 requested changes
Nice, few more cleanup things and one question

2024-04-28 16:35 UTC, gmitch215 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
Is there a reason we're on Gradle 7?

2024-04-28 16:35 UTC, gmitch215 commented on src/main/java/io/codemc/bot/menu/ApplicationMenu.java
> +    public static class Accept extends MessageContextMenu{
Could make `final`

2024-04-29 08:18 UTC, sgdc3 requested changes

2024-04-29 08:18 UTC, sgdc3 commented on src/main/resources/config.json
provide this as a "config.json.sample" file and add config.json to gitignore

2024-04-29 08:18 UTC, sgdc3 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
yeah probably we can update to gradle 8

2024-04-29 12:02 UTC, Andre601 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
I stayed on 7 because when I tried to update to 8 I received massive errors in the IDE (Apparently Maven plugin didn't want to load).

Personally, I prefer using maven over gradle to avoid all these issues I get with Gradle...

2024-05-16 12:32 UTC, Andre601 commented on src/main/java/io/codemc/bot/menu/ApplicationMenu.java
> +    public static class Accept extends MessageContextMenu{
Does it really make that much of a difference?

2024-05-16 12:39 UTC, Andre601 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
I am still unable to upgrade to Gradle 8, as I receive this error in IntelliJ 2023.6.1 (Same for 2024.1.1 which I don't use due to increased lag and RAM usage)

```
Unable to load class 'org.gradle.api.plugins.MavenPlugin'.

This is an unexpected error. Please file a bug containing the idea.log file.
```

2024-05-16 12:48 UTC, Andre601 commented on src/main/resources/config.json
I moved the default config content to config.json.sample and made a default config.json with empty/default values.

I will not however apply the config.json to the gitignore, as it would break any fork of the bot, given the above stated reason of how the config is even made.

2024-05-16 12:49 UTC, Andre601 commented on src/main/java/io/codemc/bot/menu/ApplicationMenu.java
> +    public static class Accept extends MessageContextMenu{
Applied it

2024-05-16 12:49 UTC, Andre601 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
Updated to Gradle 8 now

2024-05-16 13:18 UTC, gmitch215 commented on build.gradle
> +    id "com.github.johnrengelman.shadow" version "8.1.1"
The original shadowJar recently became EOL (see [this issue](https://github.com/johnrengelman/shadow/issues/908)), I would recommend switching to [this fork](https://plugins.gradle.org/plugin/io.github.goooler.shadow) instead so that any unexpected bugs/compatibility issues (e.g. if you want to switch to JDK 21) come up

2024-05-16 13:22 UTC, gmitch215 commented on build.gradle
>   */
Kotlin DSL might be better long-term since Groovy is dying out 🤷🏾‍♂️ but I won't push it if @sgdc3 disagrees

2024-05-16 20:19 UTC, Andre601 commented on build.gradle
>   */
sgdc3 won't be the problem here, but I will.
I will not put in the effort in moving the system around to kotlin, having to fix all kinds of stuff in the process, after already having to fix stuff from upgrading it to 8.

If you want Kotlin DSL, do it, but don't expect me to continue work on the bot after that.

2024-05-16 21:06 UTC, gmitch215 commented on build.gradle
>   */
Was just a small suggestion. You don't have to if you don't want to.

2024-05-29 00:03 UTC, Andre601 commented on build.gradle
> +    id "com.github.johnrengelman.shadow" version "8.1.1"
I feel like we can put that on the backburner for now and look at it in a future update, if really needed.

2024-07-10 17:05 UTC, sgdc3 commented on build.gradle
>   */
@Andre601 he just refers to the gradle kotlin file definition, I doubt he wants to convert the codebase to kotlin.

2024-07-10 18:19 UTC, Andre601 commented on build.gradle
>   */
> @Andre601 he just refers to the gradle kotlin file definition, I doubt he wants to convert the codebase to kotlin.

Where in my comment did I refer to the project as a whole?

2024-08-04 14:09 UTC, gmitch215 approved these changes
Missing things added in #5, LGTM

2024-11-05 21:39 UTC, merged